- name: Deploy to server
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: ${{ secrets.SERVER_HOST }} # ‚Üê DEZE MOET ER STAAN
    username: ubuntu
    key: ${{ secrets.SSH_PRIVATE_KEY }}
    script: |
      cd ~/cloudproject
      git pull origin main
      docker compose down
      docker compose up -d --build
    port: 22
